controller_list:
  - name: arm_position_controller/joint_trajectory_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints:
      - ESJoint1
      - ESJoint2
      - ESJoint3
      - ESJoint4
      - ESJoint5
      - ESJoint6
  - name: hand_controller
    type: FollowJointTrajectory
    joints:
      - _finger_joint1
      - _finger_joint2
   
