controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - ESJoint1
      - ESJoint2
      - ESJoint3
      - ESJoint4
      - ESJoint5
      - ESJoint6
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - _finger_joint1
      - _finger_joint2
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: home