arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ESJoint1
    - ESJoint2
    - ESJoint3
    - ESJoint4
    - ESJoint5
    - ESJoint6
  gains:
    ESJoint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ESJoint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ESJoint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ESJoint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ESJoint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ESJoint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
