joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_position_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
      - ESJoint1
      - ESJoint2
      - ESJoint3
      - ESJoint4
      - ESJoint5
      - ESJoint6
  constraints:
    goal_time: 2.5                   # Override default
    stopped_velocity_tolerance: 1.0 # Override default
    joint_1:
      trajectory: 1.0
